[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts","@chainlink-contracts=lib/chainlink-contracts","@chainlink-v0.8=lib/chainlink-v0.8","@chainlink-v0.7=lib/chainlink-v0.7","@chainlink-v0.6=lib/chainlink-v0.6penzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[invariant]
runs = 100
depth = 128
fail_on_revert = false 
# fail_on_revert = true #false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
